### ISSUE TITLE
CSV report columns are out by one because of comma in classification text

### ISSUE THREAD

**Issue by rifraf** [jonasblunck/ccm#11]
The code in `GetClassification` emits strings with commas. This upsets the columns in CSV files...

**Comment by jonasblunck** [comment]
That should be easy to fix, but I’m out of town this week. Feel free to create a pull request with the changes, or I can take a look next week.

Thanks,
 Jonas

Sent from my iPhone

On 19 Feb 2019, at 12:12, David Lake <notifications@github.com<mailto:notifications@github.com>> wrote:


The code in GetClassification emits strings with commas. This upsets the columns in CSV files...

**Comment by jonasblunck** [comment]
Code updated and issue fixed.
