### ISSUE TITLE
make folder configurable outside configuration file

### ISSUE THREAD

**Issue by RobertLieske** [jonasblunck/ccm#4]
I want to use the same CCM setup for several projects. Since the configuration file contains an entry for the folder, this is not applicable.

**Comment by jonasblunck** [comment]
You can pass the path to the folder to analyze as a parameter on the command line. Is that enough, or do you need the other functionality that is currently only available through the config file (like which functions to exclude, etc)?

**Comment by RobertLieske** [comment]
The documentation says: „If you specify a config file all other parameters are ignored“.
If I could mix it, ie. specify the folder on command line and take the other parameters from the config file, this would be great.
However, since you made the other required parameters available from command line, I'm already satisfied :-)

**Comment by jonasblunck** [comment]
Ok. Will close this issue as you can get the needed functionality using the other parameters.
