### ISSUE TITLE
only show complexity above threshold

### ISSUE THREAD

**Issue by RobertLieske** [jonasblunck/ccm#5]
Please allow for a threshold to be defined, below which the metric is ignored.
There is no need to show complexity 1 or 2 metrics.

**Comment by jonasblunck** [comment]
Update code to support a /threshold=intValue on command line, or a <threshold>intValue</threshold> if using a config file.

**Comment by branogoga** [comment]
Is this change included in the curent binaries of version 1.1.7?

**Comment by jonasblunck** [comment]
Hi,


You need version 1.1.10 or newer: https://github.com/jonasblunck/ccm/releases

[https://avatars3.githubusercontent.com/u/4895244?v=3&s=400]<https://github.com/jonasblunck/ccm/releases>

Releases · jonasblunck/ccm · GitHub<https://github.com/jonasblunck/ccm/releases>
github.com
Allow for the two following configuration switches to be used on command line: /threshold=5 (won't report any units that has a complexity of less than 5)




Thanks,
 Jonas

________________________________
