### ISSUE TITLE
Absolute path of file is more preffered, to make it working under jenkins/CI

### ISSUE THREAD

**Issue by NecroFilja** [jonasblunck/ccm#7]
As far as I could see file path that is saved inside of file is relative for analyzed folder.
This creates problems if analyzis started for non-root folder.
For example we have:
trunc
-ProjectFolder
-Tests
-Backups
we started ccm for For C:\jenkins\trunk-job\trunc\ProjectFolder (using xml config)
found files will be reported based in C:\jenkins\trunk-job\trunc\ProjectFolder.
For example \scripts\MainApp.js.

This creates problems for Jenkins plugins (like https://wiki.jenkins-ci.org/display/JENKINS/CCM+Plugin)
which could not display fragment of code that was affected.

Of course it could be added an option for this plugin as root folder (which is now missing) but for me it feels natural to have absolute path. Or at least option to control what path we need.

As a workaround for now I run msbuild post task that replace <file> on value from cmm.config.

**Comment by jonasblunck** [comment]
Fixed this issue so that the path passed in is maintained in report without filtering/splitting. This means you can either pass in relative paths or absolute paths and those are honored.
